---
title:  'Babynames demo'
author: 'Robert McDonald'
runtime: shiny
---

<!-- Version 0.2 -->

This uses [Hadley Wickham's](https://github.com/hadley/) R packages
[babynames](https://cran.r-project.org/package=babynames),
[ggplot2](https://cran.r-project.org/package=ggplot2), and 
[dplyr](https://cran.r-project.org/package=dplyr) to provide a
Shiny interface to the 
[Social Security names data](https://www.ssa.gov/oact/babynames/background.html). 
Lookups are case-sensitive by default. 

Code for this is available on [github](https://github.com/rmcd1024/babynames_shiny). You can post comments on github or [email me](mailto:rmcd1024@gmail.com).

Note that:

* By checking the "Partial name match" box, you will get every name which
contains the name you enter. Try entering the name "Jam" and checking the box.
* In most cases, checking the "Ignore capitalization" box will matter only when
you also check the "Partial name match" box. If you check both "Partial name
match" and "Ignore capitalization", a search for "Ja" will include "Alejandro", for example.
* The "Data" list contains all the names included in the plot

The y-axis is the proportion of babies with that name, born in that
year, who were registered for social security.

```{r, echo=FALSE, message=FALSE}
library(shiny)
library(babynames)
library(dplyr)
library(ggplot2)

minyr = min(babynames$year)
maxyr = max(babynames$year)

shinyApp(

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel(paste0("Name Popularity, ", minyr, "-", maxyr)),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         textInput("name", label="Name (case-sensitive)",
                   value='James'),
         checkboxInput("partial",
                       label='Partial name match',
                       value=FALSE),
         checkboxInput("ignorecase",
                       label='Ignore capitalization',
                       value=FALSE),
         checkboxInput("orderN",
                       label='Sort by Total',
                       value=TRUE),
         checkboxInput("showsex",
                       label="Separate names by sex", 
                       value=FALSE),
         # textOutput('test'),
         textOutput("total_n"),
         tableOutput("nametbl")
         ,textOutput("total_names")
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("namePlot", height = "600px") 
      )
   )
),

# Define server logic required to draw a histogram
server <- function(input, output) {
   output$namePlot <- renderPlot({
      # code to lookup name data and draw plot
     nametofind = ifelse(input$partial, 
                         input$name,
                         paste0("^", input$name, "$"))
     namelist = unique(grep(nametofind, babynames$name,
                     ignore.case=input$ignorecase,
                     value=TRUE))
     caption = "Popularity of"
     if (input$partial) caption = paste(caption, 'names containing')
     caption = paste(caption, input$name)
     if (input$ignorecase) caption = paste(caption, '(not case sensitive)')
     b = babynames %>% 
       filter(name %in% namelist) %>%
       group_by(name, sex, year)
     bprop = b %>% group_by(sex, year) %>%
       summarize(totprop = sum(prop))
     bdisplay = if (input$showsex) {
        b %>% 
           group_by(Name=name, Sex=sex) %>%
           summarize(Total = sum(n))
     } else {
        b %>%
           group_by(Name=name) %>%
           summarize(Total = sum(n))
     }
     output$nametbl = 
       if (input$orderN) {
         renderTable(bdisplay %>% arrange(desc(Total)))
       } else {
         renderTable(bdisplay)
       }
     output$total_names = renderText(paste0('Distinct names: ',
                                        length(unique(bdisplay$Name))))
     output$total_n = renderText(paste0('Total: ', format(sum(b$n), big.mark=',')))
     ## The plot will only display if it is the last item, which is what the
     ## function returns. If the plot is not last, it needs to be assigned to a
     ## variable and returned explicitly
     ggplot(bprop) +
       geom_point(mapping=aes(x=year, y=totprop, color=sex)) +
       labs(y='Proportion', x='Year') + 
       ggtitle(caption) +
       theme_bw() + 
       xlim(minyr, maxyr)
   },
   height=400
   )
},
     options=list(height="1000px")   

)
# Run the application 
```

